services:
  backend:
    image: dimmaryanto93/udemy-springboot-app:latest
    ports:
      - "8080:80"
    environment:
      DATABASE_HOST: 127.0.0.1
      DATABASE_PORT: 5432
      DATABASE_NAME: example
      DATABASE_PASSWORD: rahasia
      APPLICATION_PORT: 8080
    depends_on:
      - db

  db:
    image: postgres:14.2

  frontend:
    image: dimmaryanto93/udemy-angular-app:latest
    ports:
      - 80 
    environment:
      APPLICATION_PORT: 80 
      NGINX_ROOT_DOCUMENT: /var/www/html 
      BACKEND_HOST: 127.0.0.1
      BACKEND_PORT: 8080
      BACKEND_CONTEXT_PATH: / 
    depends_on:
      - backend


